// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjsV32EMKKIGfjzlmKQvDwb3pcRwVmqn0',
    appId: '1:515322724712:web:00d3c34658514283a296dd',
    messagingSenderId: '515322724712',
    projectId: 'haryanapolicedep-2cd60',
    authDomain: 'haryanapolicedep-2cd60.firebaseapp.com',
    storageBucket: 'haryanapolicedep-2cd60.appspot.com',
    measurementId: 'G-FBFLTBQKR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGRwePOcNhxxyeb5Ce2SZHVNa4Vc18xG4',
    appId: '1:515322724712:android:4eee6578c12052f6a296dd',
    messagingSenderId: '515322724712',
    projectId: 'haryanapolicedep-2cd60',
    storageBucket: 'haryanapolicedep-2cd60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgz1YcgKVTXoT_uyoZ9RJ-aXL6dDStRnI',
    appId: '1:515322724712:ios:cc0ad9690c37824fa296dd',
    messagingSenderId: '515322724712',
    projectId: 'haryanapolicedep-2cd60',
    storageBucket: 'haryanapolicedep-2cd60.appspot.com',
    iosClientId: '515322724712-40ujf2360bbahciuhou1au53itg78p75.apps.googleusercontent.com',
    iosBundleId: 'com.example.haryanaPoliceDepartment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgz1YcgKVTXoT_uyoZ9RJ-aXL6dDStRnI',
    appId: '1:515322724712:ios:cc0ad9690c37824fa296dd',
    messagingSenderId: '515322724712',
    projectId: 'haryanapolicedep-2cd60',
    storageBucket: 'haryanapolicedep-2cd60.appspot.com',
    iosClientId: '515322724712-40ujf2360bbahciuhou1au53itg78p75.apps.googleusercontent.com',
    iosBundleId: 'com.example.haryanaPoliceDepartment',
  );
}
